# Generated by Django 5.0.6 on 2024-06-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('annotation', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('color', models.IntegerField()),
                ('isComplete', models.BooleanField(default=False)),
            ],
        ),
    ]
